// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exchange_rates.sql

package sqlc

import (
	"context"
)

const getExchangeRate = `-- name: GetExchangeRate :one
SELECT rate FROM exchange_rates
WHERE base_currency = ? AND target_currency = ? AND rate_date = ?
`

type GetExchangeRateParams struct {
	BaseCurrency   string `json:"base_currency"`
	TargetCurrency string `json:"target_currency"`
	RateDate       string `json:"rate_date"`
}

func (q *Queries) GetExchangeRate(ctx context.Context, arg GetExchangeRateParams) (float64, error) {
	row := q.db.QueryRowContext(ctx, getExchangeRate, arg.BaseCurrency, arg.TargetCurrency, arg.RateDate)
	var rate float64
	err := row.Scan(&rate)
	return rate, err
}

const getLatestExchangeRateOnOrBefore = `-- name: GetLatestExchangeRateOnOrBefore :one
SELECT rate, rate_date FROM exchange_rates
WHERE base_currency = ? AND target_currency = ? AND rate_date <= ?
ORDER BY rate_date DESC
LIMIT 1
`

type GetLatestExchangeRateOnOrBeforeParams struct {
	BaseCurrency   string `json:"base_currency"`
	TargetCurrency string `json:"target_currency"`
	RateDate       string `json:"rate_date"`
}

type GetLatestExchangeRateOnOrBeforeRow struct {
	Rate     float64 `json:"rate"`
	RateDate string  `json:"rate_date"`
}

func (q *Queries) GetLatestExchangeRateOnOrBefore(ctx context.Context, arg GetLatestExchangeRateOnOrBeforeParams) (GetLatestExchangeRateOnOrBeforeRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestExchangeRateOnOrBefore, arg.BaseCurrency, arg.TargetCurrency, arg.RateDate)
	var i GetLatestExchangeRateOnOrBeforeRow
	err := row.Scan(&i.Rate, &i.RateDate)
	return i, err
}

const listExchangeRates = `-- name: ListExchangeRates :many
SELECT base_currency, target_currency, rate_date, rate, updated_at FROM exchange_rates
WHERE base_currency = ? AND rate_date = ?
`

type ListExchangeRatesParams struct {
	BaseCurrency string `json:"base_currency"`
	RateDate     string `json:"rate_date"`
}

func (q *Queries) ListExchangeRates(ctx context.Context, arg ListExchangeRatesParams) ([]ExchangeRate, error) {
	rows, err := q.db.QueryContext(ctx, listExchangeRates, arg.BaseCurrency, arg.RateDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExchangeRate{}
	for rows.Next() {
		var i ExchangeRate
		if err := rows.Scan(
			&i.BaseCurrency,
			&i.TargetCurrency,
			&i.RateDate,
			&i.Rate,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentRatePairs = `-- name: ListRecentRatePairs :many
SELECT DISTINCT base_currency, target_currency FROM exchange_rates
WHERE rate_date >= ?
`

type ListRecentRatePairsRow struct {
	BaseCurrency   string `json:"base_currency"`
	TargetCurrency string `json:"target_currency"`
}

func (q *Queries) ListRecentRatePairs(ctx context.Context, rateDate string) ([]ListRecentRatePairsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentRatePairs, rateDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentRatePairsRow{}
	for rows.Next() {
		var i ListRecentRatePairsRow
		if err := rows.Scan(&i.BaseCurrency, &i.TargetCurrency); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExchangeRate = `-- name: UpsertExchangeRate :exec
INSERT INTO exchange_rates (base_currency, target_currency, rate_date, rate, updated_at)
VALUES (?, ?, ?, ?, datetime('now'))
ON CONFLICT(base_currency, target_currency, rate_date) DO UPDATE SET
    rate = excluded.rate,
    updated_at = datetime('now')
`

type UpsertExchangeRateParams struct {
	BaseCurrency   string  `json:"base_currency"`
	TargetCurrency string  `json:"target_currency"`
	RateDate       string  `json:"rate_date"`
	Rate           float64 `json:"rate"`
}

func (q *Queries) UpsertExchangeRate(ctx context.Context, arg UpsertExchangeRateParams) error {
	_, err := q.db.ExecContext(ctx, upsertExchangeRate,
		arg.BaseCurrency,
		arg.TargetCurrency,
		arg.RateDate,
		arg.Rate,
	)
	return err
}
