import { describe, expect, it } from 'vitest';
import { getLocalDateString } from '../src/utils/date';
import {
  dateStringLacksYear,
  detectDelimiter,
  parseAmount,
  parseAmountDetailed,
  parseCSVLine,
  parseCSVRecords,
  parseDate,
  parseDateDetailed,
  parseDelimitedText,
} from '../src/services/import/parsing.js';

describe('import utils delimiter parsing', () => {
  it('detects semicolon delimiter from header', () => {
    const sample = 'Date;Payee;Amount\n2024-01-01;Coffee;-3,50\n2024-01-02;Salary;1000,00';
    expect(detectDelimiter(sample)).toBe(';');
  });

  it('detects tab delimiter from header', () => {
    const sample = 'Date\tPayee\tAmount\n2024-01-01\tCoffee\t-3.50';
    expect(detectDelimiter(sample)).toBe('\t');
  });

  it('falls back to comma when delimiter is not obvious', () => {
    expect(detectDelimiter('Only one column')).toBe(',');
  });

  it('parses semicolon-delimited lines with quoted delimiters', () => {
    const fields = parseCSVLine('"Coffee;Shop";Groceries;-23,45', ';');
    expect(fields).toEqual(['Coffee;Shop', 'Groceries', '-23,45']);
  });

  it('parses tab-delimited lines', () => {
    const fields = parseCSVLine('2024-01-01\tCoffee\t-3.50', '\t');
    expect(fields).toEqual(['2024-01-01', 'Coffee', '-3.50']);
  });

  it('ignores delimiter-like characters inside quotes while detecting', () => {
    const sample = 'Date;Memo;Amount\n2024-01-01;"Paid, in cash";-3,50';
    expect(detectDelimiter(sample)).toBe(';');
  });

  it('parses quoted multiline fields as one logical record', () => {
    const records = parseCSVRecords(
      'Date,Memo,Amount\r\n2026-08-30,"First line\r\nSecond ""quoted"" line",12.34\r\n'
    );

    expect(records).toEqual([
      ['Date', 'Memo', 'Amount'],
      ['2026-08-30', 'First line\nSecond "quoted" line', '12.34'],
    ]);
  });

  it('rejects an unterminated multiline field instead of fabricating rows', () => {
    expect(() => parseCSVRecords('Date,Memo\n2026-08-30,"unfinished')).toThrow(
      'unterminated quoted field'
    );
  });
});

describe('parseDelimitedText', () => {
  it('parses semicolon-delimited data with skipped metadata row and CRLF', () => {
    const text = [
      'Export generated by bank',
      'Date;Payee;Amount',
      '2024-01-01;Coffee;-3,50',
      '2024-01-02;Salary;1000,00',
    ].join('\r\n');

    const parsed = parseDelimitedText(text, 1);
    expect(parsed.delimiter).toBe(';');
    expect(parsed.headers).toEqual(['Date', 'Payee', 'Amount']);
    expect(parsed.rows).toEqual([
      { Date: '2024-01-01', Payee: 'Coffee', Amount: '-3,50' },
      { Date: '2024-01-02', Payee: 'Salary', Amount: '1000,00' },
    ]);
  });

  it('parses tab-delimited text including quoted tabs and escaped quotes', () => {
    const text = [
      'Date\tMemo\tAmount',
      '2024-01-01\t"He said ""hi\tthere"""\t-3.50',
      '2024-01-02\t"Salary"\t1000.00',
    ].join('\n');

    const parsed = parseDelimitedText(text);
    expect(parsed.delimiter).toBe('\t');
    expect(parsed.headers).toEqual(['Date', 'Memo', 'Amount']);
    expect(parsed.rows[0]).toEqual({
      Date: '2024-01-01',
      Memo: 'He said "hi\tthere"',
      Amount: '-3.50',
    });
  });

  it('fills missing trailing values with empty strings', () => {
    const text = ['Date;Payee;Amount', '2024-01-01;Coffee', '2024-01-02;Salary;1000,00'].join('\n');

    const parsed = parseDelimitedText(text);
    expect(parsed.rows).toEqual([
      { Date: '2024-01-01', Payee: 'Coffee', Amount: '' },
      { Date: '2024-01-02', Payee: 'Salary', Amount: '1000,00' },
    ]);
  });

  it('preserves multiline memos in parsed row objects', () => {
    const parsed = parseDelimitedText(
      'Date,Payee,Memo,Amount\n2026-08-30,Cafe,"First line\nSecond line",-12.34'
    );

    expect(parsed.rows).toEqual([
      {
        Date: '2026-08-30',
        Payee: 'Cafe',
        Memo: 'First line\nSecond line',
        Amount: '-12.34',
      },
    ]);
  });

  it('throws when skipRows consumes all non-empty lines', () => {
    const text = ['meta', 'Date;Payee;Amount'].join('\n');
    expect(() => parseDelimitedText(text, 2)).toThrow(
      'No data rows found after skipping specified rows'
    );
  });

  it('supports pipe-delimited text as fallback candidate', () => {
    const text = ['Date|Payee|Amount', '2024-01-01|Coffee|-3.50'].join('\n');
    const parsed = parseDelimitedText(text);

    expect(parsed.delimiter).toBe('|');
    expect(parsed.rows).toEqual([{ Date: '2024-01-01', Payee: 'Coffee', Amount: '-3.50' }]);
  });
});

describe('parseDate', () => {
  it('honors DD.MM.YYYY for ambiguous dates JS Date would mis-parse', () => {
    // 10.03.2026 is the canonical regression case: JS Date treats this as
    // October 3, 2026 (MM.DD.YYYY) which would land transactions in the
    // future. The configured format MUST win.
    expect(parseDate('10.03.2026', 'DD.MM.YYYY')).toBe('2026-03-10');
    expect(parseDate('11.03.2026', 'DD.MM.YYYY')).toBe('2026-03-11');
    expect(parseDate('01.03.2026', 'DD.MM.YYYY')).toBe('2026-03-01');
  });

  it('parses DD.MM.YYYY with day > 12 (which JS Date would reject)', () => {
    expect(parseDate('29.03.2026', 'DD.MM.YYYY')).toBe('2026-03-29');
    expect(parseDate('31.01.2024', 'DD.MM.YYYY')).toBe('2024-01-31');
  });

  it('parses MM/DD/YYYY format correctly', () => {
    expect(parseDate('03/10/2026', 'MM/DD/YYYY')).toBe('2026-03-10');
    expect(parseDate('12/31/2024', 'MM/DD/YYYY')).toBe('2024-12-31');
  });

  it('parses DD/MM/YYYY format correctly', () => {
    expect(parseDate('10/03/2026', 'DD/MM/YYYY')).toBe('2026-03-10');
    expect(parseDate('31/12/2024', 'DD/MM/YYYY')).toBe('2024-12-31');
  });

  it('parses YYYY-MM-DD format correctly', () => {
    expect(parseDate('2026-03-10', 'YYYY-MM-DD')).toBe('2026-03-10');
    expect(parseDate('2024-12-31', 'YYYY-MM-DD')).toBe('2024-12-31');
  });

  it('accepts mixed separators within the configured format family', () => {
    // Bank statements sometimes mix . and / — the field order is what matters.
    expect(parseDate('10/03/2026', 'DD.MM.YYYY')).toBe('2026-03-10');
    expect(parseDate('10-03-2026', 'DD.MM.YYYY')).toBe('2026-03-10');
  });

  it('rejects invalid month/day combinations', () => {
    // 30.02 doesn't exist; the format-aware parser should reject and
    // the JS Date fallback would also fail, leaving us with today.
    const result = parseDate('30.02.2026', 'DD.MM.YYYY');
    // Should not be the literal "2026-02-30" — either today or rejected.
    expect(result).not.toBe('2026-02-30');
  });

  it('handles two-digit years using a 70-cutover heuristic', () => {
    expect(parseDate('10.03.26', 'DD.MM.YYYY')).toBe('2026-03-10');
    expect(parseDate('10.03.99', 'DD.MM.YYYY')).toBe('1999-03-10');
  });

  it('returns today for empty input', () => {
    const today = getLocalDateString();
    expect(parseDate('', 'DD.MM.YYYY')).toBe(today);
  });

  // Yearless dates (e.g. "Oct 25" from CIBC statements) ──────────────────
  it('parses "Mon DD" yearless dates using defaultYear', () => {
    expect(parseDate('Oct 25', 'YYYY-MM-DD', 2025)).toBe('2025-10-25');
    expect(parseDate('Nov 05', 'YYYY-MM-DD', 2025)).toBe('2025-11-05');
    expect(parseDate('Dec 31', 'YYYY-MM-DD', 2024)).toBe('2024-12-31');
  });

  it('parses "DD Mon" yearless dates using defaultYear', () => {
    expect(parseDate('25 Oct', 'YYYY-MM-DD', 2025)).toBe('2025-10-25');
    expect(parseDate('5 November', 'YYYY-MM-DD', 2025)).toBe('2025-11-05');
  });

  it('parses full month names with no year', () => {
    expect(parseDate('October 25', 'YYYY-MM-DD', 2025)).toBe('2025-10-25');
    expect(parseDate('February 29', 'YYYY-MM-DD', 2024)).toBe('2024-02-29');
  });

  it('tolerates trailing dots after abbreviated months', () => {
    expect(parseDate('Oct. 25', 'YYYY-MM-DD', 2025)).toBe('2025-10-25');
    expect(parseDate('Sept. 30', 'YYYY-MM-DD', 2025)).toBe('2025-09-30');
  });

  it('uses current year when defaultYear is omitted', () => {
    const result = parseDate('Oct 25', 'YYYY-MM-DD');
    expect(result.startsWith(String(new Date().getFullYear()))).toBe(true);
    expect(result.endsWith('-10-25')).toBe(true);
  });

  it('rejects invalid yearless dates', () => {
    // Feb 30 doesn't exist — should fall through and not match.
    const result = parseDate('Feb 30', 'YYYY-MM-DD', 2024);
    expect(result).not.toBe('2024-02-30');
  });

  // Date cells carrying a timestamp ───────────────────────────────────────
  // Regression: bank exports put "31/01/2024 12:30" in the date column. The
  // extra field pushed the count past three, every fallback missed, and the
  // WHOLE statement imported stamped with today's date.
  it('ignores a trailing time-of-day in the date cell', () => {
    expect(parseDate('31/01/2024 12:30', 'DD/MM/YYYY')).toBe('2024-01-31');
    expect(parseDate('31/01/2024 12:30:45', 'DD/MM/YYYY')).toBe('2024-01-31');
    expect(parseDate('31.01.2024. 12:30', 'DD.MM.YYYY')).toBe('2024-01-31');
    expect(parseDate('2024-01-31 12:30:45', 'YYYY-MM-DD')).toBe('2024-01-31');
    expect(parseDate('2024-01-31T12:30:45Z', 'YYYY-MM-DD')).toBe('2024-01-31');
    expect(parseDate('01/31/2024 11:59 PM', 'MM/DD/YYYY')).toBe('2024-01-31');
    expect(parseDate('31/01/2024 12:30:45+02:00', 'DD/MM/YYYY')).toBe('2024-01-31');
  });

  it('keeps the configured field order when a time is present', () => {
    // The whole point of format-first parsing: 10/03 must stay March 10 for a
    // DD/MM user even with a timestamp attached.
    expect(parseDate('10/03/2026 08:15', 'DD/MM/YYYY')).toBe('2026-03-10');
    expect(parseDate('10/03/2026 08:15', 'MM/DD/YYYY')).toBe('2026-10-03');
  });

  // Separator-less dates ──────────────────────────────────────────────────
  it('parses compact 8-digit dates using the configured field order', () => {
    expect(parseDate('20240131', 'YYYY-MM-DD')).toBe('2024-01-31');
    expect(parseDate('31012024', 'DD/MM/YYYY')).toBe('2024-01-31');
    expect(parseDate('01312024', 'MM/DD/YYYY')).toBe('2024-01-31');
  });

  it('rejects compact 6-digit runs — indistinguishable from reference numbers', () => {
    // With the two-digit-year heuristic almost any 6-digit ID ("150323")
    // reads as a plausible date, so a mis-mapped reference column would
    // import as scattered fabricated dates. Better to warn than to invent.
    expect(parseDateDetailed('310124', 'DD/MM/YYYY').ok).toBe(false);
    expect(parseDateDetailed('150323', 'DD/MM/YYYY').ok).toBe(false);
    expect(parseDateDetailed('240131', 'YYYY-MM-DD').ok).toBe(false);
  });

  it('rejects digit runs that are not a valid compact date', () => {
    // 5 or 7 digits isn't a date, and 20241331 has no month 13.
    expect(parseDateDetailed('12345', 'YYYY-MM-DD').ok).toBe(false);
    expect(parseDateDetailed('20241331', 'YYYY-MM-DD').ok).toBe(false);
  });

  it('reads a bare 4-digit year as January 1 of that year', () => {
    // Pre-existing behavior via new Date('2024'), kept but written out
    // directly so it can't shift a day for users west of UTC.
    expect(parseDate('2024', 'YYYY-MM-DD')).toBe('2024-01-01');
    expect(parseDateDetailed('1999', 'DD/MM/YYYY')).toEqual({
      date: '1999-01-01',
      ok: true,
      empty: false,
    });
    // Out-of-range 4-digit runs are NOT years.
    expect(parseDateDetailed('0042', 'YYYY-MM-DD').ok).toBe(false);
    expect(parseDateDetailed('9999', 'YYYY-MM-DD').ok).toBe(false);
  });
});

describe('parseDateDetailed', () => {
  it('flags an empty cell as empty, not as a real date', () => {
    const result = parseDateDetailed('   ', 'DD/MM/YYYY');
    expect(result).toEqual({ date: getLocalDateString(), ok: false, empty: true });
  });

  it('flags a present-but-unreadable cell without claiming it is empty', () => {
    const result = parseDateDetailed('n/a', 'DD/MM/YYYY');
    expect(result.ok).toBe(false);
    expect(result.empty).toBe(false);
    expect(result.date).toBe(getLocalDateString());
  });

  it('reports ok for dates it actually read', () => {
    expect(parseDateDetailed('31/01/2024', 'DD/MM/YYYY')).toEqual({
      date: '2024-01-31',
      ok: true,
      empty: false,
    });
    expect(parseDateDetailed('Oct 25', 'YYYY-MM-DD', 2025).ok).toBe(true);
    expect(parseDateDetailed('Jan 31, 2024', 'DD/MM/YYYY').ok).toBe(true);
  });

  it('reports ok when the input genuinely is today', () => {
    // The today fallback and a real import of today must be distinguishable.
    const result = parseDateDetailed(getLocalDateString(), 'YYYY-MM-DD');
    expect(result.ok).toBe(true);
    expect(result.date).toBe(getLocalDateString());
  });
});

describe('dateStringLacksYear', () => {
  it('returns true for "Mon DD" style dates', () => {
    expect(dateStringLacksYear('Oct 25')).toBe(true);
    expect(dateStringLacksYear('Nov 05')).toBe(true);
    expect(dateStringLacksYear('October 25')).toBe(true);
    expect(dateStringLacksYear('Sept. 30')).toBe(true);
  });

  it('returns true for "DD Mon" style dates', () => {
    expect(dateStringLacksYear('25 Oct')).toBe(true);
    expect(dateStringLacksYear('5 November')).toBe(true);
  });

  it('returns false for dates that include a 4-digit year', () => {
    expect(dateStringLacksYear('Oct 25 2025')).toBe(false);
    expect(dateStringLacksYear('2025-10-25')).toBe(false);
    expect(dateStringLacksYear('25/10/2025')).toBe(false);
    expect(dateStringLacksYear('10.03.2026')).toBe(false);
  });

  it('returns false for numeric dates with 2-digit year', () => {
    expect(dateStringLacksYear('10.03.26')).toBe(false);
    expect(dateStringLacksYear('25/10/25')).toBe(false);
  });

  it('returns false for empty or garbage input', () => {
    expect(dateStringLacksYear('')).toBe(false);
    expect(dateStringLacksYear('   ')).toBe(false);
    expect(dateStringLacksYear('hello world')).toBe(false);
  });
});

describe('parseAmount', () => {
  const us = { thousandSeparator: ',', decimalSeparator: '.' };
  const eu = { thousandSeparator: '.', decimalSeparator: ',' };

  it('parses US format with currency code prefix', () => {
    expect(parseAmount('RSD 123,234.90', us)).toBe(123234.9);
    expect(parseAmount('USD 1,500.00', us)).toBe(1500);
  });

  it('parses EU format with currency code prefix', () => {
    expect(parseAmount('RSD 1.123,98', eu)).toBe(1123.98);
    expect(parseAmount('EUR 1.500,00', eu)).toBe(1500);
  });

  it('parses currency code as suffix', () => {
    expect(parseAmount('123,234.90 RSD', us)).toBe(123234.9);
    expect(parseAmount('1.123,98 RSD', eu)).toBe(1123.98);
  });

  it('parses currency code with no space', () => {
    expect(parseAmount('RSD123,234.90', us)).toBe(123234.9);
    expect(parseAmount('1.123,98RSD', eu)).toBe(1123.98);
  });

  it('parses currency symbols', () => {
    expect(parseAmount('$1,500.00', us)).toBe(1500);
    expect(parseAmount('€1.500,00', eu)).toBe(1500);
    expect(parseAmount('£99.99', us)).toBe(99.99);
  });

  it('parses plain numbers without currency', () => {
    expect(parseAmount('123,234.90', us)).toBe(123234.9);
    expect(parseAmount('1.123,98', eu)).toBe(1123.98);
    expect(parseAmount('0,00', eu)).toBe(0);
  });

  it('parses large amounts with multiple thousand separators', () => {
    expect(parseAmount('RSD 1,234,567.89', us)).toBe(1234567.89);
    expect(parseAmount('1.234.567,89 EUR', eu)).toBe(1234567.89);
  });

  it('detects negatives via leading minus', () => {
    expect(parseAmount('-1,500.00', us, true)).toBe(-1500);
    expect(parseAmount('-RSD 1.500,00', eu, true)).toBe(-1500);
  });

  it('detects negatives via parentheses', () => {
    expect(parseAmount('(1,500.00)', us, true)).toBe(-1500);
    expect(parseAmount('(RSD 1.500,00)', eu, true)).toBe(-1500);
  });

  it('detects negatives via trailing minus', () => {
    expect(parseAmount('1,500.00-', us, true)).toBe(-1500);
  });

  it('detects a minus that sits after the currency symbol', () => {
    // "$-54.20" used to import as INCOME: the sign check required the minus at
    // position 0, so the value was read as negative and then absolute-valued
    // back to positive. A single mapped Amount column turns that into an
    // inflow — the spend shows up as money in.
    expect(parseAmount('$-54.20', us, true)).toBe(-54.2);
    expect(parseAmount('USD -1,500.00', us, true)).toBe(-1500);
    expect(parseAmount('RSD -1.500,00', eu, true)).toBe(-1500);
    // The already-working orderings must stay working.
    expect(parseAmount('-$54.20', us, true)).toBe(-54.2);
    expect(parseAmount('-54.20', us, true)).toBe(-54.2);
  });

  it('treats Unicode dashes as a minus sign', () => {
    // PDF text layers emit U+2212 and friends. These were stripped as
    // "currency symbols", losing the sign entirely.
    expect(parseAmount('−54.20', us, true)).toBe(-54.2); // U+2212 minus
    expect(parseAmount('− 54.20', us, true)).toBe(-54.2);
    expect(parseAmount('–1,500.00', us, true)).toBe(-1500); // en dash
    expect(parseAmount('—1,500.00', us, true)).toBe(-1500); // em dash
    expect(parseAmount('1.500,00−', eu, true)).toBe(-1500); // trailing U+2212
    expect(parseAmount('－54.20', us, true)).toBe(-54.2); // U+FF0D fullwidth (CJK)
    expect(parseAmount('‐54.20', us, true)).toBe(-54.2); // U+2010 hyphen
  });

  it('reads the Dutch/German ",–" whole-amount suffix as ",00", not a minus', () => {
    // "12,–" means exactly 12.00 — the dash after the decimal separator
    // stands for the zero cents. It must never negate the amount.
    expect(parseAmount('12,–', eu, true)).toBe(12); // en dash
    expect(parseAmount('12,-', eu, true)).toBe(12); // ASCII hyphen
    expect(parseAmount('1.234,–', eu, true)).toBe(1234);
    expect(parseAmount('12.-', us, true)).toBe(12);
    // A genuinely negative whole amount keeps its leading sign.
    expect(parseAmount('-12,-', eu, true)).toBe(-12);
    // Trailing minus with digits before it is still a minus.
    expect(parseAmount('54.20-', us, true)).toBe(-54.2);
  });

  it('keeps positive amounts positive', () => {
    expect(parseAmount('+2,450.00', us, true)).toBe(2450);
    expect(parseAmount('2,450.00', us, true)).toBe(2450);
    expect(parseAmount('$2,450.00', us, true)).toBe(2450);
    expect(parseAmount('1.500,00 EUR', eu, true)).toBe(1500);
  });

  it('does not read a lone dash as an amount', () => {
    // Statements use "-" / "—" as an empty-cell placeholder. It must stay a
    // parse failure, not become zero or a sign.
    expect(parseAmountDetailed('-', us).ok).toBe(false);
    expect(parseAmountDetailed('—', us).ok).toBe(false);
    expect(parseAmountDetailed('−', us).ok).toBe(false);
  });

  it('returns absolute value when preserveSign is false', () => {
    expect(parseAmount('-1,500.00', us)).toBe(1500);
    expect(parseAmount('(1,500.00)', us)).toBe(1500);
  });

  it('handles no decimal portion', () => {
    expect(parseAmount('RSD 100', us)).toBe(100);
    expect(parseAmount('1.500 EUR', eu)).toBe(1500);
  });

  it('handles whitespace and trailing junk gracefully', () => {
    expect(parseAmount('  RSD  1.500,00  ', eu)).toBe(1500);
    expect(parseAmount('RSD 1.500,00*', eu)).toBe(1500);
  });

  it('returns 0 for empty input', () => {
    expect(parseAmount('', us)).toBe(0);
    expect(parseAmount('   ', us)).toBe(0);
  });
});

describe('parseAmountDetailed', () => {
  const us = { thousandSeparator: ',', decimalSeparator: '.' };

  it('marks empty/whitespace cells as empty (not a parse error)', () => {
    expect(parseAmountDetailed('', us)).toEqual({ value: 0, ok: false, empty: true });
    expect(parseAmountDetailed('   ', us)).toEqual({ value: 0, ok: false, empty: true });
  });

  it('treats a genuine zero as parseable — the "$0.00 should be parsable" fix', () => {
    expect(parseAmountDetailed('$0.00', us)).toEqual({ value: 0, ok: true, empty: false });
    expect(parseAmountDetailed('0', us)).toEqual({ value: 0, ok: true, empty: false });
    expect(parseAmountDetailed('0.00', us)).toEqual({ value: 0, ok: true, empty: false });
  });

  it('flags present-but-unparseable values as errors (ok:false, empty:false)', () => {
    for (const garbage of ['Pending', 'N/A', 'n/a', '--']) {
      const result = parseAmountDetailed(garbage, us);
      expect(result.ok).toBe(false);
      expect(result.empty).toBe(false);
      expect(result.value).toBe(0);
    }
  });

  it('parses real values, honoring sign', () => {
    expect(parseAmountDetailed('-1,800.00', us, true)).toEqual({
      value: -1800,
      ok: true,
      empty: false,
    });
    expect(parseAmountDetailed('2450.00', us)).toEqual({ value: 2450, ok: true, empty: false });
  });

  it('keeps parseAmount backward compatible (0 for empty and garbage)', () => {
    expect(parseAmount('', us)).toBe(0);
    expect(parseAmount('Pending', us)).toBe(0);
    expect(parseAmount('$0.00', us)).toBe(0);
    expect(parseAmount('-1,800.00', us, true)).toBe(-1800);
  });

  it('strips currency text and parses per the SELECTED format (no guessing)', () => {
    const eu = { thousandSeparator: '.', decimalSeparator: ',' };
    // Honors the user's chosen format: comma decimal under EU, dot decimal under US.
    expect(parseAmountDetailed('EUR 23,23', eu)).toMatchObject({ value: 23.23, ok: true });
    expect(parseAmountDetailed('24.43 EUR', us)).toMatchObject({ value: 24.43, ok: true });
    expect(parseAmountDetailed('E 24.6', us)).toMatchObject({ value: 24.6, ok: true });
    // A mismatched format yields a different value, by design — the data is not
    // dropped, it follows the selected separators.
    expect(parseAmountDetailed('EUR 23,23', us).value).toBe(2323);
  });
});
